# Generated by Django 5.0.3 on 2024-06-12 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SizeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('MICRO', 'Micro'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='smeapp.province')),
            ],
        ),
        migrations.CreateModel(
            name='SME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sme_ref_number', models.CharField(unique=True)),
                ('company', models.CharField()),
                ('contact_person', models.CharField(unique=True)),
                ('phone_number', models.CharField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField()),
                ('sector', models.CharField()),
                ('sex', models.CharField()),
                ('age', models.CharField()),
                ('disability', models.CharField()),
                ('type_of_business', models.CharField()),
                ('product_service', models.CharField()),
                ('export', models.CharField()),
                ('comments', models.CharField()),
                ('number_of_employees', models.IntegerField()),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('annual_revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.province')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('size_of_annual_revenue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_revenue_scale', to='smeapp.sizevalue')),
                ('size_of_asset_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_value_scale', to='smeapp.sizevalue')),
                ('size_of_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_size_scale', to='smeapp.sizevalue')),
                ('size_of_employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_scale', to='smeapp.sizevalue')),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_scale', to='smeapp.sme')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='smeapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ward_level', models.BooleanField(default=False)),
                ('is_district_level', models.BooleanField(default=False)),
                ('is_province_level', models.BooleanField(default=False)),
                ('is_national_level', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeapp.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeapp.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeapp.ward')),
            ],
        ),
        migrations.AddField(
            model_name='sme',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.ward'),
        ),
    ]
