# Generated by Django 5.0.3 on 2024-05-21 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SizeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('MICRO', 'Micro'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.province')),
            ],
        ),
        migrations.CreateModel(
            name='SME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('sector', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=4)),
                ('type_of_business', models.CharField(max_length=100)),
                ('product_service', models.CharField(max_length=500)),
                ('number_of_employees', models.IntegerField()),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.province')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('size_of_annual_revenue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_revenue_scale', to='smeapp.sizevalue')),
                ('size_of_asset_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_value_scale', to='smeapp.sizevalue')),
                ('size_of_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_size_scale', to='smeapp.sizevalue')),
                ('size_of_employees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_scale', to='smeapp.sizevalue')),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_scale', to='smeapp.sme')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeapp.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeapp.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sme',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smeapp.userprofile'),
        ),
    ]
