# Generated by Django 5.0.3 on 2024-05-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='disability',
            field=models.CharField(max_length=50),
        ),
    ]
