# Generated by Django 5.0.3 on 2024-04-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sme',
            old_name='size_of_busines',
            new_name='size_of_business',
        ),
    ]
