# Generated by Django 5.0.3 on 2024-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='age',
            field=models.IntegerField(),
        ),
    ]
