# Generated by Django 5.0.3 on 2024-05-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sme',
            old_name='exports',
            new_name='export',
        ),
    ]
