# Generated by Django 5.0.3 on 2025-01-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme',
            name='compliance',
            field=models.CharField(default='ZIMRA', max_length=255),
        ),
    ]
