# Generated by Django 5.0.3 on 2024-05-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smeapp.userprofile'),
        ),
    ]
