# Generated by Django 5.0.3 on 2025-01-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0002_sme_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme',
            name='registration',
            field=models.CharField(default='Registered', max_length=255),
        ),
        migrations.AddField(
            model_name='sme',
            name='tax',
            field=models.CharField(default='Presumptive Tax', max_length=255),
        ),
    ]
