# Generated by Django 5.0.3 on 2025-01-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0002_alter_sme_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme',
            name='source_of_funds',
            field=models.CharField(default='Business grants', max_length=255),
        ),
        migrations.AddField(
            model_name='sme',
            name='training_recieved',
            field=models.CharField(default=5, max_length=255),
        ),
    ]
