# Generated by Django 5.0.3 on 2024-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0002_alter_sme_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='age',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='annual_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sme',
            name='asset_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sme',
            name='comments',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='company',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='contact_person',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='disability',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='export',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='phone_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='product_service',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='sector',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='sex',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sme',
            name='type_of_business',
            field=models.CharField(),
        ),
    ]
