# Generated by Django 5.0.3 on 2024-04-30 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0002_rename_size_of_busines_sme_size_of_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sme',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.province'),
        ),
        migrations.AlterField(
            model_name='sme',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.province'),
        ),
    ]
