# Generated by Django 5.0.3 on 2025-01-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0003_sme_source_of_funds_sme_training_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='compliance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sme',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sme',
            name='registration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sme',
            name='source_of_funds',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sme',
            name='tax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sme',
            name='training',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sme',
            name='training_recieved',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
