# Generated by Django 5.0.3 on 2025-01-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0003_sme_registration_sme_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='sme',
            name='education',
            field=models.CharField(default='Received Education', max_length=255),
        ),
        migrations.AddField(
            model_name='sme',
            name='training',
            field=models.CharField(default='Received Training', max_length=255),
        ),
    ]
