# Generated by Django 5.0.3 on 2024-05-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0003_district_province_alter_sme_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='size_of_business',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
