# Generated by Django 5.0.3 on 2024-05-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0004_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smeapp.ward'),
        ),
    ]
