# Generated by Django 5.0.3 on 2024-05-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0005_sizevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='size_of_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smeapp.sizevalue'),
        ),
    ]
