# Generated by Django 5.0.3 on 2024-05-21 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0006_sme_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='smeapp.province'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='smeapp.district'),
        ),
    ]
