# Generated by Django 5.0.3 on 2024-05-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0007_alter_district_province_alter_ward_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='province_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='ward_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.province'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.district'),
        ),
    ]
