# Generated by Django 5.0.3 on 2024-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0008_alter_sizevalue_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevalue',
            name='size',
            field=models.CharField(choices=[('MICRO', 'Micro'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10),
        ),
    ]
