# Generated by Django 5.0.3 on 2024-05-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0008_rename_district_name_district_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='district_name',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='name',
            new_name='province_name',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='name',
            new_name='ward_name',
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='smeapp.province'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='smeapp.district'),
        ),
    ]
