# Generated by Django 5.0.3 on 2024-05-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0009_rename_name_district_district_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sme',
            name='user_profile',
        ),
    ]
