# Generated by Django 5.0.3 on 2024-05-05 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0009_alter_sizevalue_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('business_size', models.CharField(max_length=20)),
                ('size_of_annual_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_sizes', to='smeapp.sizevalue')),
                ('size_of_asset_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_sizes', to='smeapp.sizevalue')),
                ('size_of_employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_sizes', to='smeapp.sizevalue')),
                ('sme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smeapp.sme')),
            ],
        ),
    ]
