# Generated by Django 5.0.3 on 2024-05-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0012_alter_calculationscale_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sme',
            name='size_of_business',
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='business_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_of_business', to='smeapp.sizevalue'),
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
