# Generated by Django 5.0.3 on 2024-05-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0013_remove_sme_size_of_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationscale',
            name='sme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_scale', to='smeapp.sme'),
        ),
    ]
