# Generated by Django 5.0.3 on 2024-05-12 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0014_alter_calculationscale_sme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationscale',
            old_name='business_size',
            new_name='size_of_business',
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_annual_revenue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_revenue', to='smeapp.sizevalue'),
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_asset_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_value', to='smeapp.sizevalue'),
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_size', to='smeapp.sizevalue'),
        ),
    ]
