# Generated by Django 5.0.3 on 2024-05-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0015_rename_business_size_calculationscale_size_of_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_annual_revenue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_of_annual_revenue', to='smeapp.sizevalue'),
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_asset_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_of_asset_value', to='smeapp.sizevalue'),
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_of_employees', to='smeapp.sizevalue'),
        ),
    ]
