# Generated by Django 5.0.3 on 2024-05-12 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeapp', '0016_alter_calculationscale_size_of_annual_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_annual_revenue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_revenue_scale', to='smeapp.sizevalue'),
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_asset_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_value_scale', to='smeapp.sizevalue'),
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_size_scale', to='smeapp.sizevalue'),
        ),
        migrations.AlterField(
            model_name='calculationscale',
            name='size_of_employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees_scale', to='smeapp.sizevalue'),
        ),
    ]
